version: '3.5'

services:
  exams_backend:
    &exams_backend
    build: .
    image: exams-backend
    container_name: exams-backend
    networks:
      - exams
    entrypoint: /app/docker-entrypoint.sh
    command: rails server -b 0.0.0.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - postgresql
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
  postgresql:
    image: postgres:15
    container_name: exams_db
    networks:
      - exams
    restart: "no"
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: exams_backend_development
      POSTGRES_USER: exams
      POSTGRES_PASSWORD: exams
    volumes:
      - exams_backend_development:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    container_name: exams_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    env_file: .env
    networks:
      - exams


  worker:
    <<: *exams_backend
    container_name: exams-worker
    command: bundle exec sidekiq
    depends_on:
      - exams_backend
      - postgresql
      - redis
    ports: []
    entrypoint: ""

volumes:
  exams_backend_development:
  bundle:
  redis_data:

networks:
  exams:
    name: exams
    driver: bridge
